<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Rstolsmark.UnifiClient</PackageId>
    <Version>1.0.4</Version>
    <Authors>ragnarstolsmark</Authors>
    <Company>Rstolsmark</Company>
    <Description>A Unifi Client library.</Description>
    <PackageTags>unifi</PackageTags>
    <RepositoryUrl>https://github.com/ragnarstolsmark/Rstolsmark.UnifiClient</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>
  
</Project>
